from kitti_model_config import kitti_model_config
from kitti_vgg16_config import kitti_vgg16_config
from kitti_res50_config import kitti_res50_config
from kitti_squeezeDet_config import kitti_squeezeDet_config
from kitti_squeezeDet_config import get_debug_val
from kitti_squeezeDet_config import get_debug_val_name
from kitti_squeezeDetPlus_config import kitti_squeezeDetPlus_config
from kitti_mobileDet_config import kitti_mobileDet_config
from kitti_mobileDet_config import kitti_mobileDet_V1_025_config
from vkitti_mobileDet_config import vkitti_mobileDet_config
from vkitti_mobileDet_config import vkitti_mobileDet_V1_025_config
from vkitti_SSD_config import vkitti_SSD_config

